id = "ruby"
name = "Ruby"
version = "0.3.3"
schema_version = 1
description = "Ruby support."
repository = "https://github.com/zed-extensions/ruby"
authors = ["Vitaly Slobodin <vitaliy.slobodin@gmail.com>"]
themes = []
languages = ["languages/erb", "languages/ruby", "languages/rbs"]

[lib]
kind = "Rust"
version = "0.2.0"

[grammars.embedded_template]
repository = "https://github.com/tree-sitter/tree-sitter-embedded-template"
rev = "91fc5ae1140d5c9d922312431f7d251a48d7b8ce"

[grammars.rbs]
repository = "https://github.com/joker1007/tree-sitter-rbs"
rev = "8d8e65ac3f77fbc9e15b1cdb9f980a3e0ac3ab99"

[grammars.ruby]
repository = "https://github.com/tree-sitter/tree-sitter-ruby"
rev = "7dbc1e2d0e2d752577655881f73b4573f3fe85d4"

[language_servers.rubocop]
languages = ["Ruby"]

[language_servers.rubocop.language_ids]

[language_servers.ruby-lsp]
languages = ["Ruby", "ERB"]

[language_servers.ruby-lsp.language_ids]

[language_servers.solargraph]
languages = ["Ruby"]

[language_servers.solargraph.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
