
[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

startup_mode = "Maximized"

[font]

normal.family = "ShureTechMono Nerd Font"
bold.family = "ShureTechMono Nerd Font"
italic.family = "ShureTechMono Nerd Font"
bold_italic.family = "ShureTechMono Nerd Font"

size = 12.0

[general]
live_config_reload = true
import = ["~/.cache/wal/colors-alacritty.toml"]
