id = "ultimate-dark-neo"
name = "Ultimate Dark Neo"
version = "0.0.5"
schema_version = 1
description = "A muted and pleasant dark theme for Zed with some italics to distinguish certain parts of the syntax. Designed for use with the programming font Victor Mono."
repository = "https://github.com/rubjo/ultimate-dark-neo-zed"
authors = ["Rune B"]
themes = ["themes/Ultimate Dark Neo.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
