id = "tmux"
name = "tmux"
version = "0.0.2"
schema_version = 1
description = "Syntax highlighting for tmux configuration files"
repository = "https://github.com/dangh/zed-tmux"
authors = ["Dang Huynh <huynhminhdang@gmail.com>"]
themes = []
languages = ["languages/tmux"]

[lib]

[grammars.tmux]
repository = "https://github.com/Freed-Wu/tree-sitter-tmux"
rev = "7499587642a46ee156e1bb58851904ac750dcc7c"

[language_servers]

[slash_commands]

[indexed_docs_providers]
