id = "v"
name = "V (Vlang)"
version = "0.3.0"
schema_version = 1
description = "V language support."
repository = "https://github.com/lv37/zed-v"
authors = ["lv37 <132778382+lv37@users.noreply.github.com>"]
themes = []
languages = ["languages/v"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.v]
repository = "https://github.com/lv37/v-tree-sitter"
rev = "764882164bcc91414a7cf861bfe495847f6dff87"

[language_servers.v]
languages = ["V"]

[language_servers.v.language_ids]

[slash_commands]

[indexed_docs_providers]
