id = "less"
name = "LESS"
version = "0.0.1"
schema_version = 1
description = "LESS language support"
repository = "https://github.com/jimliang/zed-less"
authors = ["jimliang <769925821@qq.com>"]
themes = []
languages = ["languages/less"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.less]
repository = "https://github.com/jimliang/tree-sitter-less"
rev = "307541e7b4d9d890a0d85bd9acf7da777d26d323"

[language_servers.less-language-server]
language = "LESS"
languages = []

[language_servers.less-language-server.language_ids]

[slash_commands]
