id = "one-dark-pro"
name = "One Dark Pro"
version = "0.0.8"
schema_version = 1
description = "A port of VSCode One Dark Pro with some tweaks"
repository = "https://github.com/mordfustang21/zed-one-dark-pro"
authors = ["MordFustang21"]
themes = ["themes/one-dark.json"]
languages = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
