id = "elixir"
name = "Elixir"
version = "0.1.3"
schema_version = 1
description = "Elixir support."
repository = "https://github.com/zed-industries/zed"
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
themes = []
languages = ["languages/heex", "languages/elixir"]

[lib]
kind = "Rust"
version = "0.2.0"

[grammars.elixir]
repository = "https://github.com/elixir-lang/tree-sitter-elixir"
rev = "a2861e88a730287a60c11ea9299c033c7d076e30"

[grammars.heex]
repository = "https://github.com/phoenixframework/tree-sitter-heex"
rev = "2e1348c3cf2c9323e87c2744796cf3f3868aa82a"

[language_servers.elixir-ls]
languages = ["Elixir", "HEEX"]

[language_servers.elixir-ls.language_ids]

[language_servers.lexical]
languages = ["Elixir", "HEEX"]

[language_servers.lexical.language_ids]

[language_servers.next-ls]
languages = ["Elixir", "HEEX"]

[language_servers.next-ls.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
