id = "autocorrect"
name = "AutoCorrect"
version = "0.1.0"
schema_version = 1
description = "AutoCorrect is a linter and formatter to help you to improve copywriting, correct spaces, words, and punctuations between CJK (Chinese, Japanese, Korean)."
repository = "https://github.com/huacnlee/zed-autocorrect"
authors = ["Jason Lee <huacnlee@gmail.com>"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.6"

[grammars]

[language_servers.autocorrect]
languages = ["HTML", "JSON", "ERB", "Markdown", "JavaScript", "TypeScript", "CSS", "JSX", "TSX", "Vue.js", "YAML", "TOML", "XML", "Rust", "Ruby", "Python", "Go", "SQL", "Plain Text", "Unknow"]
code_action_kinds = ["quickfix"]

[language_servers.autocorrect.language_ids]
