id = "neocmake"
name = "NeoCMake"
version = "0.0.5"
schema_version = 1
description = "CMake grammar and lsp with neocmakelsp"
repository = "https://github.com/k0tran/zed_neocmake"
authors = ["Sorochan Ilya <sorochanilyav@gmail.com>"]
themes = []
languages = ["languages/cmake"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.cmake]
repository = "https://github.com/uyha/tree-sitter-cmake"
rev = "47564fb0045710aaaa26b4972f4f986297a78280"

[language_servers.cmake]
language = "CMake"
languages = []

[language_servers.cmake.language_ids]

[slash_commands]

[indexed_docs_providers]
