id = "lua"
name = "Lua"
version = "0.1.1"
schema_version = 1
description = "Lua support."
repository = "https://github.com/zed-industries/zed"
authors = ["Max Brunsfeld <max@zed.dev>"]
themes = []
languages = ["languages/lua"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
rev = "a24dab177e58c9c6832f96b9a73102a0cfbced4a"

[language_servers.lua-language-server]
language = "Lua"
languages = []

[language_servers.lua-language-server.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
