-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
vim.cmd("set nocompatible")
vim.cmd("set showmatch")
vim.cmd("set ignorecase")
vim.cmd("set mouse=v")
vim.cmd("set hlsearch")
vim.cmd("set incsearch")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set expandtab")
vim.cmd("set shiftwidth=4")
vim.cmd("set autoindent")
vim.cmd("set number")
vim.cmd("set wildmode=longest,list")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("syntax on")
vim.cmd("set mouse=a")
vim.cmd("filetype plugin on")
vim.cmd("set cursorline")
vim.cmd("set ttyfast")
vim.cmd("filetype plugin indent on")
vim.cmd("set spell")
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
vim.cmd("set termguicolors")
-- require("keymaps")
-- require("options")
-- require("misc")
