id = "fish"
name = "Fish"
version = "0.0.8"
schema_version = 0
description = "Fish language support for Zed"
repository = "https://github.com/hasit/zed-fish"
authors = ["Hasit Mistry <hasitnm@gmail.com>"]
themes = []
languages = ["languages/fish"]

[lib]

[grammars.fish]
repository = "https://github.com/ram02z/tree-sitter-fish"
rev = "a78aef9abc395c600c38a037ac779afc7e3cc9e0"

[language_servers]
