id = "swift"
name = "Swift"
version = "0.3.2"
schema_version = 1
description = "Swift support."
repository = "https://github.com/zed-extensions/swift"
authors = ["ejjonny <https://github.com/ejjonny>", "Samuser107 L.Longheval <samuser107@gmail.com>"]
themes = []
languages = ["languages/swift"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.swift]
repository = "https://github.com/alex-pinkus/tree-sitter-swift"
rev = "33e56e4e2a6455f3fd4e04cfe5c7a314d498612d"

[language_servers.sourcekit-lsp]
language = "Swift"
languages = []

[language_servers.sourcekit-lsp.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
