id = "cspell"
name = "CSpell"
version = "0.0.1"
schema_version = 1
description = "CSpell Language Server for Zed editor"
repository = "https://github.com/mantou132/zed-cspell"
authors = ["mantou132 <709922234@qq.com>"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.1.0"

[grammars]

[language_servers.cspell]
languages = ["AsciiDoc", "Astro", "Bash", "Biome", "C", "C#", "C++", "Clojure", "CSharp", "CSS", "CSV", "D", "Dart", "Deno", "Docker", "Elixir", "Elm", "Emmet", "Erlang", "Fish", "FSharp", "GDScript", "Git Commit", "Gleam", "GLSL", "Go", "GraphQL", "Groovy", "Haskell", "HEEX", "HTML", "Hy", "Idris", "Java", "JavaScript", "JSON", "JSONC", "Julia", "Kotlin", "LaTeX", "Lua", "Luau", "Makefile", "Markdown", "Nim", "Nix", "OCaml", "PHP", "Plain Text", "Prisma", "Proto", "PureScript", "Python", "R", "Racket", "Rego", "reST", "ReStructuredText", "Roc", "Ruby", "Rust", "Scala", "Scheme", "SCSS", "Shell Script", "SQL", "Svelte", "Swift", "TailwindCSS", "Terraform", "TOML", "TSX", "TypeScript", "Uiua", "Vue", "WIT", "XML", "YAML", "Yarn", "Zig"]

[language_servers.cspell.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
