always_on_top = true
auto_start_work_timer = true
auto_start_break_timer = true
desktop_notifications = true
focus_duration = 1500
long_break_duration = 1200
max_round_number = 4
minimize_to_tray = true
minimize_to_tray_on_close = true
muted = false
short_break_duration = 300
theme = "gruvbox"
tick_sounds_during_work = true
tick_sounds_during_break = true
