id = "perl"
name = "Perl"
version = "0.1.0"
schema_version = 1
description = "Perl support"
repository = "https://github.com/tree-sitter-perl/zed-perl"
authors = ["Veesh <rabbiveesh@gmail.com>"]
themes = []
languages = ["languages/perl"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.perl]
repository = "https://github.com/tree-sitter-perl/tree-sitter-perl"
rev = "465983954cae2d2f984eae82de5ed5f11ca291dc"

[language_servers.perlnavigator-server]
language = "Perl"
languages = []

[language_servers.perlnavigator-server.language_ids]

[slash_commands]

[indexed_docs_providers]
