id = "make"
name = "Make"
version = "1.0.1"
schema_version = 1
description = "Makefile syntax highlighting"
repository = "https://github.com/caius/zed-make"
authors = ["Caius Durling <dev@caius.name>", "d1y <chenhonzhou@gmail.com>", "Marshall Bowers <elliott.codes@gmail.com>"]
themes = []
languages = ["languages/make"]

[lib]

[grammars.make]
repository = "https://github.com/caius/tree-sitter-make"
rev = "b35c2714e73d2846b26061b06cda4fa56d61e3a5"

[language_servers]
