id = "python-refactoring"
name = "PythonRefactoring"
version = "0.0.3"
schema_version = 1
description = "Refactoring support for Python."
repository = "https://github.com/rowillia/zed-python-refactoring"
authors = ["Roy Williams <roy.williams.iii@gmail.com>"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.6"

[grammars]

[language_servers.python-refactoring]
languages = ["Python"]

[language_servers.python-refactoring.language_ids]

[slash_commands]

[indexed_docs_providers]
