id = "luau"
name = "Luau"
version = "0.2.2"
schema_version = 1
description = "Luau support."
repository = "https://github.com/4teapo/zed-luau"
authors = ["teapo <4teapo@gmail.com>"]
themes = []
languages = ["languages/luau"]

[lib]
kind = "Rust"
version = "0.2.0"

[grammars.luau]
repository = "https://github.com/4teapo/tree-sitter-luau"
rev = "cd500d82bb278092f3b42dfdb4965eca0fe3b45e"

[language_servers.luau-lsp]
language = "Luau"
languages = []

[language_servers.luau-lsp.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
