[colors.primary]
background = "#151311"
foreground = "#c4c4c3"

[colors.cursor]
text = "#151311"
cursor = "#c4c4c3"

[colors.vi_mode_cursor]
text = "#151311"
cursor = "#c4c4c3"

[colors.search.matches]
foreground = "#151311"
background = "#c4c4c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6f645a"
background = "#c4c4c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#151311"
red = "#926E5F"
green = "#D7724A"
yellow = "#CD6B52"
blue = "#798672"
magenta = "#999273"
cyan = "#DAB071"
white = "#c4c4c3"

[colors.bright]
black = "#6f645a"
red = "#926E5F"
green = "#D7724A"
yellow = "#CD6B52"
blue = "#798672"
magenta = "#999273"
cyan = "#DAB071"
white = "#c4c4c3"

[colors.dim]
black = "#c4c4c3"
red = "#926E5F"
green = "#999273"
yellow = "#CD6B52"
blue = "#798672"
magenta = "#D7724A"
cyan = "#DAB071"
white = "#6f645a"

