# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/wallpaper/default.jpg"

# Special
background='#151311'
foreground='#c4c4c3'
cursor='#c4c4c3'

# Colors
color0='#151311'
color1='#926E5F'
color2='#D7724A'
color3='#CD6B52'
color4='#798672'
color5='#999273'
color6='#DAB071'
color7='#c4c4c3'
color8='#6f645a'
color9='#926E5F'
color10='#D7724A'
color11='#CD6B52'
color12='#798672'
color13='#999273'
color14='#DAB071'
color15='#c4c4c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
