id = "sorbet"
name = "Sorbet"
version = "0.1.0"
schema_version = 1
description = "LSP support for Ruby + Sorbet"
repository = "https://github.com/notchairmk/zed-sorbet"
authors = ["Taylor Chaparro <taylorchprr@gmail.com>"]
themes = []
languages = ["languages/ruby"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.ruby]
repository = "https://github.com/tree-sitter/tree-sitter-ruby"
rev = "71bd32fb7607035768799732addba884a37a6210"

[language_servers.sorbet]
languages = ["Ruby"]

[language_servers.sorbet.language_ids]

[slash_commands]

[indexed_docs_providers]
