id = "quakec"
name = "QuakeC"
version = "0.0.2"
schema_version = 1
description = "Zed language support for the QuakeC language"
repository = "https://github.com/schraf/zed-quakec"
authors = ["Marc Schraffenberger <marc@schraffenberger.com>"]
themes = []
languages = ["languages/quakec"]

[lib]

[grammars.quakec]
repository = "https://github.com/vkazanov/tree-sitter-quakec"
rev = "268be403609e944a45e5620c49cbbd6683b7f676"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
