id = "tailwind-theme"
name = "Tailwind Syntax"
version = "0.5.0"
schema_version = 1
description = "Tailwind theme for Zed"
repository = "https://github.com/biaqat/tailwind-theme-zed"
authors = ["blaqat <blaqat.ag@gmail.com>"]
themes = ["themes/tailwind.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
