id = "meson"
name = "Meson"
version = "0.2.0"
schema_version = 1
description = "Meson language support for the Zed editor"
repository = "https://codeberg.org/hanna/zed-meson"
authors = ["hanna rose <hanna@hanna.lol>"]
themes = []
languages = ["languages/meson"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.meson]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-meson"
rev = "bd17c824196ce70800f64ad39cfddd1b17acc13f"

[language_servers.meson]
languages = ["Meson"]

[language_servers.meson.language_ids]

[slash_commands]

[indexed_docs_providers]
