id = "elisp"
name = "Elisp"
version = "0.0.4"
schema_version = 1
description = "Elisp language support for Zed"
repository = "https://github.com/JosephTLyons/zed-elisp"
authors = ["Joseph Lyons <JosephTLyons@gmail.com>"]
themes = []
languages = ["languages/elisp"]

[lib]

[grammars.elisp]
repository = "https://github.com/Wilfred/tree-sitter-elisp"
rev = "e5524fdccf8c22fc726474a910e4ade976dfc7bb"

[language_servers]
