id = "palenight"
name = "Palenight Theme"
version = "0.0.1"
schema_version = 1
description = "The popular Palenight theme now in Zed!"
repository = "https://github.com/alanmontgomery/palenight-zed"
authors = ["Alan Montgomery <alanmontgomerycoding@gmail.com>"]
themes = ["themes/palenight.json"]
languages = []

[lib]

[grammars]

[language_servers]
