id = "activitywatch"
name = "activitywatch"
version = "0.1.1"
schema_version = 1
description = "ActivityWatch watcher support"
repository = "https://github.com/sachk/aw-watcher-zed"
authors = ["Sacha Korban sk@sachk.com"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.2.0"

[grammars]

[language_servers.activitywatch]
languages = ["AsciiDoc", "Astro", "Bash", "Biome", "C", "C++", "Clojure", "CSharp", "CSS", "CSV", "D", "Dart", "Elixir", "Elm", "Erlang", "Fish", "FSharp", "GDScript", "Gleam", "Go", "GraphQL", "Haskell", "HEEX", "HTML", "Hy", "Idris", "Java", "JavaScript", "JSON", "JSONC", "Julia", "Kotlin", "Lua", "Markdown", "Nim", "Nix", "OCaml", "PureScript", "Python", "Racket", "Roc", "Ruby", "Rust", "Scheme", "SCSS", "Shell Script", "SQL", "Swift", "TOML", "TSX", "TypeScript", "WIT", "XML", "YAML", "Zig"]

[language_servers.activitywatch.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
