id = "java"
name = "Java"
version = "5.0.1"
schema_version = 1
description = "Java support."
repository = "https://github.com/zed-extensions/java"
authors = ["Valentine Briese <valentinegb@icloud.com>", "Samuser107 L.Longheval <samuser107@gmail.com>", "Yury Abykhodau <abehodau@gmail.com>"]
themes = []
languages = ["languages/java"]

[lib]
kind = "Rust"
version = "0.2.0"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
rev = "94703d5a6bed02b98e438d7cad1136c01a60ba2c"

[language_servers.jdtls]
language = "Java"
languages = []

[language_servers.jdtls.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
