id = "astro"
name = "Astro"
version = "0.1.3"
schema_version = 1
description = "Astro support."
repository = "https://github.com/zed-extensions/astro"
authors = ["Alvaro Gaona <alvgaona@gmail.com>", "0xk1f0 <dev@k1f0.dev>"]
themes = []
languages = ["languages/astro"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.astro]
repository = "https://github.com/virchau13/tree-sitter-astro"
rev = "4be180759ec13651f72bacee65fa477c64222a1a"

[language_servers.astro-language-server]
language = "Astro"
languages = []

[language_servers.astro-language-server.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
