id = "pylsp"
name = "Python LSP"
version = "0.0.1"
schema_version = 1
description = "python-lsp extension for Zed"
repository = "https://github.com/rgbkrk/python-lsp-zed-extension"
authors = ["Kyle Kelley <rgbkrk@gmail.com>"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.6"

[grammars]

[language_servers.pylsp]
languages = ["Python"]

[language_servers.pylsp.language_ids]

[slash_commands]

[indexed_docs_providers]
