id = "xml"
name = "XML"
version = "0.0.8"
schema_version = 1
description = "XML syntax support."
repository = "https://github.com/sweetppro/zed-xml"
authors = ["sweetppro"]
themes = []
languages = ["languages/xml"]

[lib]

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
rev = "4b64dd3a03ec002258d6268d712fd93716d6ab57"
path = "xml"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
