id = "devicetree"
name = "devicetree"
version = "0.0.1"
schema_version = 1
description = "DeviceTree syntax highlight"
repository = "https://github.com/anikinmd/zed_devicetree"
authors = ["Mikhail Anikin <anikin.mikhail.d@gmail.com>"]
themes = []
languages = ["languages/devicetree"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.devicetree]
repository = "https://github.com/joelspadin/tree-sitter-devicetree"
rev = "296b3c294a8bcfca6673296d99f9cd37049b8026"

[language_servers.devicetree]
languages = ["devicetree"]

[language_servers.devicetree.language_ids]

[slash_commands]

[indexed_docs_providers]
