id = "zen-abyssal"
name = "Zen Abyssal"
version = "0.1.0"
schema_version = 1
description = "A theme you'll probably like for zed."
repository = "https://github.com/KevInCompile/ZenAbyssal"
authors = ["KevInCompile <kevcoc10@gmail.com>"]
themes = ["themes/zen-abyssal.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
