id = "zig"
name = "Zig"
version = "0.3.2"
schema_version = 1
description = "Zig support."
repository = "https://github.com/zed-industries/zed"
authors = ["Allan Calix <contact@acx.dev>"]
themes = []
languages = ["languages/zig"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.zig]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-zig"
rev = "eb7d58c2dc4fbeea4745019dee8df013034ae66b"

[language_servers.zls]
language = "Zig"
languages = []

[language_servers.zls.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
