id = "groovy"
name = "Groovy"
version = "1.1.0"
schema_version = 1
description = "Groovy support."
repository = "https://github.com/valentinegb/zed-groovy"
authors = ["Valentine Briese <valentinegb@icloud.com>"]
themes = []
languages = ["languages/groovy"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.groovy]
repository = "https://github.com/murtaza64/tree-sitter-groovy"
rev = "6c5c8813233fe326e24c5ef032858d13f8006a8d"

[language_servers.groovy]
language = "Groovy"
languages = []

[language_servers.groovy.language_ids]
