id = "gleam"
name = "Gleam"
version = "0.2.1"
schema_version = 1
description = "Gleam support."
repository = "https://github.com/gleam-lang/zed-gleam"
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
themes = []
languages = ["languages/gleam"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.gleam]
repository = "https://github.com/gleam-lang/tree-sitter-gleam"
rev = "426e67087fd62be5f4533581b5916b2cf010fb5b"

[language_servers.gleam]
language = "Gleam"
languages = []

[language_servers.gleam.language_ids]

[slash_commands.gleam-project]
description = "Returns information about the current Gleam project."
requires_argument = false

[indexed_docs_providers.gleam-hexdocs]
