id = "snippets"
name = "Snippets"
version = "0.0.5"
schema_version = 1
description = "Support for language-agnostic snippets, provided by simple-completion-language-server"
repository = "https://github.com/zed-industries/zed"
authors = []
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.6"

[grammars]

[language_servers.snippet-completion-server]
languages = ["Astro", "Clojure", "C", "C++", "C#", "Dart", "Dockerfile", "Elixir", "Elm", "ERB", "Erlang", "Gleam", "GLSL", "Go", "Haskell", "HCL", "HEEX", "HTML", "JavaScript", "JSDoc", "JSON", "Lua", "Markdown", "OCaml", "PHP", "Python", "Prisma", "PureScript", "Racket", "Ruby", "Rust", "Scheme", "Shell Script", "Svelte", "Terraform", "TOML", "TypeScript", "TSX", "Uiua", "Vue.js", "Zig"]

[language_servers.snippet-completion-server.language_ids]
TypeScript = "typescript"
"Vue.js" = "vue"
Terraform = "terraform"
TSX = "typescriptreact"
PHP = "php"
HTML = "html"
CSS = "css"
"Terraform Vars" = "terraform-vars"
JavaScript = "javascript"

[slash_commands]
