id = "terraform"
name = "Terraform"
version = "0.1.1"
schema_version = 1
description = "Terraform support."
repository = "https://github.com/zed-industries/zed"
authors = ["Caius Durling <dev@caius.name>", "Daniel Banck <dbanck@users.noreply.github.com>"]
themes = []
languages = ["languages/terraform-vars", "languages/terraform", "languages/hcl"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.hcl]
repository = "https://github.com/MichaHoffmann/tree-sitter-hcl"
rev = "e936d3fef8bac884661472dce71ad82284761eb1"

[language_servers.terraform-ls]
languages = ["Terraform", "Terraform Vars"]
code_action_kinds = []

[language_servers.terraform-ls.language_ids]
Terraform = "terraform"
"Terraform Vars" = "terraform-vars"

[slash_commands]

[indexed_docs_providers]
