[colors.primary]
background = '#10141c'
foreground = '#c3c4c6'

[colors.cursor]
text = '#c3c4c6'
cursor = '#c3c4c6'

[colors.normal]
black = '#10141c'
red = '#494857'
green = '#4A576C'
yellow = '#5C5A6C'
blue = '#A5706A'
magenta = '#566D8D'
cyan = '#637A9D'
white = '#c3c4c6'

[colors.bright]
black = '#5c6471'
red = '#494857'
green = '#4A576C'
yellow = '#5C5A6C'
blue = '#A5706A'
magenta = '#566D8D'
cyan = '#637A9D'
white = '#c3c4c6'
