# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/wallpaper/port.png"

# Special
background='#191d24'
foreground='#c5c6c8'
cursor='#c5c6c8'

# Colors
color0='#191d24'
color1='#5E7CA1'
color2='#708797'
color3='#7592A5'
color4='#91999E'
color5='#AFB0AE'
color6='#C3BAB1'
color7='#c5c6c8'
color8='#616a77'
color9='#5E7CA1'
color10='#708797'
color11='#7592A5'
color12='#91999E'
color13='#AFB0AE'
color14='#C3BAB1'
color15='#c5c6c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
