[colors.primary]
background = "#0f1010"
foreground = "#c3c3c3"

[colors.cursor]
text = "#0f1010"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#0f1010"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#0f1010"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c5959"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f1010"
red = "#777B72"
green = "#948B77"
yellow = "#8FC17B"
blue = "#3E8285"
magenta = "#458588"
cyan = "#749D91"
white = "#c3c3c3"

[colors.bright]
black = "#6c5959"
red = "#777B72"
green = "#948B77"
yellow = "#8FC17B"
blue = "#3E8285"
magenta = "#458588"
cyan = "#749D91"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#777B72"
green = "#458588"
yellow = "#8FC17B"
blue = "#3E8285"
magenta = "#948B77"
cyan = "#749D91"
white = "#6c5959"

