[colors.primary]
background = "#10141b"
foreground = "#c3c4c6"

[colors.cursor]
text = "#10141b"
cursor = "#c3c4c6"

[colors.vi_mode_cursor]
text = "#10141b"
cursor = "#c3c4c6"

[colors.search.matches]
foreground = "#10141b"
background = "#c3c4c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c6570"
background = "#c3c4c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#10141b"
red = "#80807F"
green = "#797C83"
yellow = "#7E8187"
blue = "#8B8E92"
magenta = "#A5A8AE"
cyan = "#BABEC5"
white = "#c3c4c6"

[colors.bright]
black = "#5c6570"
red = "#80807F"
green = "#797C83"
yellow = "#7E8187"
blue = "#8B8E92"
magenta = "#A5A8AE"
cyan = "#BABEC5"
white = "#c3c4c6"

[colors.dim]
black = "#c3c4c6"
red = "#80807F"
green = "#A5A8AE"
yellow = "#7E8187"
blue = "#8B8E92"
magenta = "#797C83"
cyan = "#BABEC5"
white = "#5c6570"

