[colors.primary]
background = '#121414'
foreground = '#c3c4c4'

[colors.cursor]
text = '#c3c4c4'
cursor = '#c3c4c4'

[colors.normal]
black = '#121414'
red = '#DE9D1F'
green = '#D89921'
yellow = '#918B54'
blue = '#497E81'
magenta = '#3A838D'
cyan = '#458588'
white = '#c3c4c4'

[colors.bright]
black = '#5a6f6f'
red = '#DE9D1F'
green = '#D89921'
yellow = '#918B54'
blue = '#497E81'
magenta = '#3A838D'
cyan = '#458588'
white = '#c3c4c4'
