[colors.primary]
background = '#0f1010'
foreground = '#c3c3c3'

[colors.cursor]
text = '#c3c3c3'
cursor = '#c3c3c3'

[colors.normal]
black = '#0f1010'
red = '#777B72'
green = '#948B77'
yellow = '#8FC17B'
blue = '#3E8285'
magenta = '#458588'
cyan = '#749D91'
white = '#c3c3c3'

[colors.bright]
black = '#6c5959'
red = '#777B72'
green = '#948B77'
yellow = '#8FC17B'
blue = '#3E8285'
magenta = '#458588'
cyan = '#749D91'
white = '#c3c3c3'
