[colors.primary]
background = '#111313'
foreground = '#c3c4c4'

[colors.cursor]
text = '#c3c4c4'
cursor = '#c3c4c4'

[colors.normal]
black = '#111313'
red = '#656158'
green = '#6C7268'
yellow = '#B15A44'
blue = '#788873'
magenta = '#ABA06F'
cyan = '#848881'
white = '#c3c4c4'

[colors.bright]
black = '#5a6e6e'
red = '#656158'
green = '#6C7268'
yellow = '#B15A44'
blue = '#788873'
magenta = '#ABA06F'
cyan = '#848881'
white = '#c3c4c4'
