[colors.primary]
background = "#101212"
foreground = "#c3c3c3"

[colors.cursor]
text = "#101212"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#101212"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#101212"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#596d6d"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#101212"
red = "#3F8288"
green = "#478789"
yellow = "#739C90"
blue = "#83A598"
magenta = "#9EAA95"
cyan = "#C9D1A8"
white = "#c3c3c3"

[colors.bright]
black = "#596d6d"
red = "#3F8288"
green = "#478789"
yellow = "#739C90"
blue = "#83A598"
magenta = "#9EAA95"
cyan = "#C9D1A8"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#3F8288"
green = "#9EAA95"
yellow = "#739C90"
blue = "#83A598"
magenta = "#478789"
cyan = "#C9D1A8"
white = "#596d6d"

