--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/wallpaper/earth-in-space.png"

-- Special
background="#10141b"
foreground="#c3c4c6"
cursor="#c3c4c6"

-- Colors
color0="#10141b"
color1="#80807F"
color2="#797C83"
color3="#7E8187"
color4="#8B8E92"
color5="#A5A8AE"
color6="#BABEC5"
color7="#c3c4c6"
color8="#5c6570"
color9="#80807F"
color10="#797C83"
color11="#7E8187"
color12="#8B8E92"
color13="#A5A8AE"
color14="#BABEC5"
color15="#c3c4c6"
