# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/wallpaper/triangle.jpg"

# Special
background='#101012'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#101012'
color1='#817D69'
color2='#979274'
color3='#90908F'
color4='#B2AF8E'
color5='#C3BD90'
color6='#D7D19F'
color7='#c3c3c3'
color8='#59596d'
color9='#817D69'
color10='#979274'
color11='#90908F'
color12='#B2AF8E'
color13='#C3BD90'
color14='#D7D19F'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
