[colors.primary]
background = '#111212'
foreground = '#c3c3c3'

[colors.cursor]
text = '#c3c3c3'
cursor = '#c3c3c3'

[colors.normal]
black = '#111212'
red = '#556E6A'
green = '#57847C'
yellow = '#6E827C'
blue = '#3E8585'
magenta = '#488687'
cyan = '#709A92'
white = '#c3c3c3'

[colors.bright]
black = '#6e5959'
red = '#556E6A'
green = '#57847C'
yellow = '#6E827C'
blue = '#3E8585'
magenta = '#488687'
cyan = '#709A92'
white = '#c3c3c3'
