[colors.primary]
background = '#181818'
foreground = '#c5c5c5'

[colors.cursor]
text = '#c5c5c5'
cursor = '#c5c5c5'

[colors.normal]
black = '#181818'
red = '#689D6A'
green = '#D69821'
yellow = '#988D73'
blue = '#437E80'
magenta = '#458588'
cyan = '#B9AD8F'
white = '#c5c5c5'

[colors.bright]
black = '#725d5d'
red = '#689D6A'
green = '#D69821'
yellow = '#988D73'
blue = '#437E80'
magenta = '#458588'
cyan = '#B9AD8F'
white = '#c5c5c5'
