# Shell variables
# Generated by 'wal'
wallpaper="/home/kirk/wallpaper/Evangelion.png"

# Special
background='#0f0f0f'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#0f0f0f'
color1='#933737'
color2='#A23D3D'
color3='#994848'
color4='#7B7F80'
color5='#7C8080'
color6='#8D8D8D'
color7='#c3c3c3'
color8='#6c5959'
color9='#933737'
color10='#A23D3D'
color11='#994848'
color12='#7B7F80'
color13='#7C8080'
color14='#8D8D8D'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
