[colors.primary]
background = '#0f0f0e'
foreground = '#c3c3c2'

[colors.cursor]
text = '#c3c3c2'
cursor = '#c3c3c2'

[colors.normal]
black = '#0f0f0e'
red = '#C8AE36'
green = '#8D8A76'
yellow = '#788486'
blue = '#8F9187'
magenta = '#ADAD95'
cyan = '#AEAF99'
white = '#c3c3c2'

[colors.bright]
black = '#6c6c58'
red = '#C8AE36'
green = '#8D8A76'
yellow = '#788486'
blue = '#8F9187'
magenta = '#ADAD95'
cyan = '#AEAF99'
white = '#c3c3c2'
