[colors.primary]
background = '#101012'
foreground = '#c3c3c3'

[colors.cursor]
text = '#c3c3c3'
cursor = '#c3c3c3'

[colors.normal]
black = '#101012'
red = '#817D69'
green = '#979274'
yellow = '#90908F'
blue = '#B2AF8E'
magenta = '#C3BD90'
cyan = '#D7D19F'
white = '#c3c3c3'

[colors.bright]
black = '#59596d'
red = '#817D69'
green = '#979274'
yellow = '#90908F'
blue = '#B2AF8E'
magenta = '#C3BD90'
cyan = '#D7D19F'
white = '#c3c3c3'
