[colors.primary]
background = '#191d24'
foreground = '#c5c6c8'

[colors.cursor]
text = '#c5c6c8'
cursor = '#c5c6c8'

[colors.normal]
black = '#191d24'
red = '#5E7CA1'
green = '#708797'
yellow = '#7592A5'
blue = '#91999E'
magenta = '#AFB0AE'
cyan = '#C3BAB1'
white = '#c5c6c8'

[colors.bright]
black = '#616a77'
red = '#5E7CA1'
green = '#708797'
yellow = '#7592A5'
blue = '#91999E'
magenta = '#AFB0AE'
cyan = '#C3BAB1'
white = '#c5c6c8'
