[colors.primary]
background = '#0E1318'
foreground = '#c2c4c5'

[colors.cursor]
text = '#c2c4c5'
cursor = '#c2c4c5'

[colors.normal]
black = '#0E1318'
red = '#6C7269'
green = '#7C8375'
yellow = '#888A7A'
blue = '#A7A992'
magenta = '#C0BFA3'
cyan = '#D6D5B4'
white = '#c2c4c5'

[colors.bright]
black = '#5a646f'
red = '#6C7269'
green = '#7C8375'
yellow = '#888A7A'
blue = '#A7A992'
magenta = '#C0BFA3'
cyan = '#D6D5B4'
white = '#c2c4c5'
