--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/wallpaper/Evangelion.png"

-- Special
background="#0f0f0f"
foreground="#c3c3c3"
cursor="#c3c3c3"

-- Colors
color0="#0f0f0f"
color1="#933737"
color2="#A23D3D"
color3="#994848"
color4="#7B7F80"
color5="#7C8080"
color6="#8D8D8D"
color7="#c3c3c3"
color8="#6c5959"
color9="#933737"
color10="#A23D3D"
color11="#994848"
color12="#7B7F80"
color13="#7C8080"
color14="#8D8D8D"
color15="#c3c3c3"
