[colors.primary]
background = '#121313'
foreground = '#c3c4c4'

[colors.cursor]
text = '#c3c4c4'
cursor = '#c3c4c4'

[colors.normal]
black = '#121313'
red = '#749E92'
green = '#86A994'
yellow = '#ADAF94'
blue = '#C7B899'
magenta = '#AEC692'
cyan = '#DFD6AC'
white = '#c3c4c4'

[colors.bright]
black = '#5a6e6e'
red = '#749E92'
green = '#86A994'
yellow = '#ADAF94'
blue = '#C7B899'
magenta = '#AEC692'
cyan = '#DFD6AC'
white = '#c3c4c4'
