[colors.primary]
background = '#0f0f0f'
foreground = '#c3c3c3'

[colors.cursor]
text = '#c3c3c3'
cursor = '#c3c3c3'

[colors.normal]
black = '#0f0f0f'
red = '#933737'
green = '#A23D3D'
yellow = '#994848'
blue = '#7B7F80'
magenta = '#7C8080'
cyan = '#8D8D8D'
white = '#c3c3c3'

[colors.bright]
black = '#6c5959'
red = '#933737'
green = '#A23D3D'
yellow = '#994848'
blue = '#7B7F80'
magenta = '#7C8080'
cyan = '#8D8D8D'
white = '#c3c3c3'
