[colors.primary]
background = '#0f1111'
foreground = '#c3c3c3'

[colors.cursor]
text = '#c3c3c3'
cursor = '#c3c3c3'

[colors.normal]
black = '#0f1111'
red = '#B36543'
green = '#B7934F'
yellow = '#66938C'
blue = '#9A9D8B'
magenta = '#85A597'
cyan = '#BCAD93'
white = '#c3c3c3'

[colors.bright]
black = '#596d6d'
red = '#B36543'
green = '#B7934F'
yellow = '#66938C'
blue = '#9A9D8B'
magenta = '#85A597'
cyan = '#BCAD93'
white = '#c3c3c3'
