--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kirk/wallpaper/space_odyssey.jpg"

-- Special
background="#0f1111"
foreground="#c3c3c3"
cursor="#c3c3c3"

-- Colors
color0="#0f1111"
color1="#B36543"
color2="#B7934F"
color3="#66938C"
color4="#9A9D8B"
color5="#85A597"
color6="#BCAD93"
color7="#c3c3c3"
color8="#596d6d"
color9="#B36543"
color10="#B7934F"
color11="#66938C"
color12="#9A9D8B"
color13="#85A597"
color14="#BCAD93"
color15="#c3c3c3"
