id = "brainfuck"
name = "Brainfuck"
version = "0.0.4"
schema_version = 1
description = "Brainfuck language support for Zed"
repository = "https://github.com/JosephTLyons/zed-brainfuck"
authors = ["Joseph Lyons <JosephTLyons@gmail.com>"]
themes = []
languages = ["languages/brainfuck"]

[lib]

[grammars.brainfuck]
repository = "https://github.com/reo101/tree-sitter-brainfuck"
rev = "9e5d80bca5ff890ae59e5adde35914668d0aa4ea"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
