id = "gruvbox-ish"
name = "Gruvbox ish"
version = "0.0.1"
schema_version = 1
description = "Gruvbox ish theme from VSCode ported to zed."
repository = "https://github.com/LeoDog896/zed-gruvbox-ish"
authors = ["Tristan F. <leodog896@gmail.ocm>"]
themes = ["themes/gruvbox-ish.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
