# "$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_6)\
$os\
$username\
[](bg:color_10 fg:color_6)\
$directory\
[](fg:color_10 bg:color_4)\
$git_branch\
$git_status\
[](fg:color_4 bg:color_3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_3 bg:color_2)\
$docker_context\
$conda\
[](fg:color_3 bg:color_0)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'wal_source'

[Wal-source]
color_fg = '    #c2c3c3'
color_0 = '    #0d0f10'
color_2 = '    #BB8D3F'
color_3 = '    #AF8C54'
color_4 = '    #B19D7E'
color_5 = '    #C39143'
color_6 = '    #B29E80'
color_8 = '    #586b6b'
color_9 = '    #CA6555'
color_10 = '    #CA6555'

[os]
disabled = false
style = "bg:color_6 fg:color_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "💩"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_6 fg:color_fg"
style_root = "bg:color_6 fg:color_fg"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg bg:color_10"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_4"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_3)]($style)'

[c]
symbol = " "
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_3)]($style)'

[rust]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_3)]($style)'

[golang]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_3)]($style)'

[php]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_3)]($style)'

[python]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg"
format = '[[ $symbol( $context) ](fg:#83 a598 bg:color_2)]($style)'

[conda]
style = "bg:color_2"
format = '[[ $symbol( $environment) ](fg:color_2 bg:color_2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_4)'
error_symbol = '[](bold fg:color_9)'
vimcmd_symbol = '[](bold fg:color_4)'
vimcmd_replace_one_symbol = '[](bold fg:color_8)'
vimcmd_replace_symbol = '[](bold fg:color_8)'
vimcmd_visual_symbol = '[](bold fg:color_10:w
)'
