id = "odin"
name = "Odin"
version = "0.2.0"
schema_version = 1
description = "Odin support."
repository = "https://github.com/rxptr/zed-odin"
authors = ["Mo Nematzadeh <mohammad.h.nematzadeh@gmail.com>"]
themes = []
languages = ["languages/odin"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.odin]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-odin"
rev = "e4897cd9b73e35d80bdb89ff4b0c62606435837f"

[language_servers.ols]
language = "Odin"
languages = []

[language_servers.ols.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
